# Generated by Django 4.1 on 2022-08-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, verbose_name='Category'),
        ),
    ]
